# Generated by Django 4.0.5 on 2022-06-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('sku', models.CharField(db_index=True, max_length=12)),
                ('price', models.IntegerField()),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
