# Generated by Django 4.0.5 on 2022-06-15 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wishes', '0003_remove_wishlist_product_remove_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistproduct',
            old_name='wish_list',
            new_name='wishlist',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(default=list, through='wishes.WishListProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlistproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
