# Generated by Django 4.0.5 on 2022-06-15 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('wishes', '0004_rename_wish_list_wishlistproduct_wishlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(default=list, related_name='products', through='wishes.WishListProduct', to=settings.AUTH_USER_MODEL),
        ),
    ]
