# Generated by Django 4.0.5 on 2022-06-15 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
        ('wishes', '0005_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ManyToManyField(default=list, through='wishes.WishListProduct', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlistproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_products', to='products.product'),
        ),
    ]
