# Generated by Django 4.0.5 on 2022-06-16 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishes', '0008_alter_wishlistproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistproduct',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
